pub fn create_order_handler() {}
pub fn list_table_handler() {}
pub fn create_table_handler() {}
pub fn list_menu_handler() {}
pub fn create_menu_handler() {}
pub fn list_order_handler() {}
pub fn delete_order_item_handler() {}
pub fn list_order_items_for_table_handler() {}
pub fn get_order_item_for_table_handler() {}
